CREATE TABLE IF NOT EXISTS courses (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  category VARCHAR(100) NOT NULL,
  instructor VARCHAR(100) NOT NULL,
  price INT NOT NULL,
  old_price INT NOT NULL,
  rating DECIMAL(3,1) DEFAULT 0,
  reviews INT DEFAULT 0,
  lessons INT DEFAULT 0,
  hours INT DEFAULT 0,
  description TEXT,
  short_desc TEXT,
  fullDescription TEXT,
  long_desc TEXT,
  image VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO courses (id, name, category, instructor, price, old_price, rating, reviews, lessons, hours, description, short_desc, fullDescription, long_desc, image) VALUES (1, 'Video Editing Pro', 'Video Editing', 'สมชาย แก้ว', 1299, 1999, 4.8, 250, 12, 24, 'เรียนรู้เทคนิคการตัดต่อวิดีโอขั้นสูง ใช้ Adobe Premiere Pro และเทคนิคมืออาชีพในการแก้ไขวิดีโอ', 'เรียนรู้เทคนิคการตัดต่อวิดีโอขั้นสูง ใช้ Adobe Premiere Pro', 'คอร์สนี้ครอบคลุมเทคนิคการตัดต่อวิดีโอทั้งขั้นพื้นฐานและขั้นสูง ตั้งแต่การปรับปรุงพื้นฐานไปจนถึงการใช้เอฟเฟกต์พิเศษและการสร้างแอนิเมชั่น', 'คอร์สนี้ครอบคลุมเทคนิคการตัดต่อวิดีโอทั้งขั้นพื้นฐานและขั้นสูง ตั้งแต่การปรับปรุงพื้นฐานไปจนถึงการใช้เอฟเฟกต์พิเศษและการสร้างแอนิเมชั่น ที่จะทำให้วิดีโอของคุณดูเป็นมืออาชีพมากยิ่งขึ้น', '🎬');
INSERT INTO courses (id, name, category, instructor, price, old_price, rating, reviews, lessons, hours, description, short_desc, fullDescription, long_desc, image) VALUES (2, 'Color Grading Masterclass', 'Advanced Color Grading', 'ธวัชชัย ศิริ', 1599, 2599, 4.9, 180, 15, 30, 'เทคนิกปรับสีระดับมืออาชีพสำหรับภาพยนตร์', 'เทคนิกปรับสีระดับมืออาชีพสำหรับภาพยนตร์', 'เรียนรู้วิธีปรับสีและโทนเพื่อให้ภาพยนตร์ของคุณดูมืออาชีพและน่าดึงดูด', 'เรียนรู้วิธีปรับสีและโทนเพื่อให้ภาพยนตร์ของคุณดูมืออาชีพและน่าดึงดูด ด้วยเทคนิค Color Grading ขั้นสูง', '🎨');
INSERT INTO courses (id, name, category, instructor, price, old_price, rating, reviews, lessons, hours, description, short_desc, fullDescription, long_desc, image) VALUES (3, 'Motion Graphics Design', 'Motion Graphics', 'ณัฐปอ สิทธิพล', 1899, 2999, 4.7, 165, 18, 36, 'สร้างแอนิเมชั่น 2D/3D ที่สวยงามด้วย After Effects', 'สร้างแอนิเมชั่น 2D/3D ที่สวยงามด้วย After Effects', 'คอร์สสอนการสร้างกราฟิกแบบเคลื่อนไหวที่สวยงามเพื่อใช้ในโปรโมชั่นและคลิป', 'คอร์สสอนการสร้างกราฟิกแบบเคลื่อนไหวที่สวยงามเพื่อใช้ในโปรโมชั่นและคลิป เพิ่มความน่าสนใจให้ชิ้นงานของคุณ', '✨');
INSERT INTO courses (id, name, category, instructor, price, old_price, rating, reviews, lessons, hours, description, short_desc, fullDescription, long_desc, image) VALUES (4, 'Digital Marketing Bootcamp', 'Digital Marketing', 'นพดล ธรรมรักษ์', 1299, 1999, 4.8, 320, 20, 40, 'เทคนิกการตลาดดิจิทัลครบถ้วนตั้งแต่ SEO ถึง Social Media', 'เทคนิกการตลาดดิจิทัลครบถ้วนตั้งแต่ SEO ถึง Social Media', 'เรียนรู้กลยุทธ์การตลาดดิจิทัลทั้งหมด ตั้งแต่การเพิ่มอันดับใน SEO ไปจนถึงการจัดการสื่อสังคม', 'เรียนรู้กลยุทธ์การตลาดดิจิทัลทั้งหมด ตั้งแต่การเพิ่มอันดับใน SEO ไปจนถึงการจัดการสื่อสังคม เพื่อเพิ่มยอดขายและสร้างการรับรู้แบรนด์', '📱');
INSERT INTO courses (id, name, category, instructor, price, old_price, rating, reviews, lessons, hours, description, short_desc, fullDescription, long_desc, image) VALUES (5, 'Build Your Personal Brand', 'Personal Branding', 'วิชิต สุมนา', 999, 1599, 4.9, 210, 16, 28, 'สร้างแบรนด์ส่วนตัวของคุณให้เป็นที่รู้จักในโลกดิจิทัล', 'สร้างแบรนด์ส่วนตัวของคุณให้เป็นที่รู้จักในโลกดิจิทัล', 'สอนวิธีสร้างและพัฒนาแบรนด์ส่วนตัวของคุณให้เป็นที่รู้จัก', 'สอนวิธีสร้างและพัฒนาแบรนด์ส่วนตัวของคุณให้เป็นที่รู้จัก สร้างความน่าเชื่อถือและดึงดูดผู้ติดตาม', '⭐');
INSERT INTO courses (id, name, category, instructor, price, old_price, rating, reviews, lessons, hours, description, short_desc, fullDescription, long_desc, image) VALUES (6, 'Sales Copywriting Secrets', 'Copywriting Mastery', 'นิชา ธัญชนก', 799, 1299, 4.8, 190, 14, 22, 'เขียนสัญญาณขายที่ดึงดูดกระตุ้นการซื้อได้อย่างมีประสิทธิ', 'เขียนสัญญาณขายที่ดึงดูดกระตุ้นการซื้อได้อย่างมีประสิทธิ', 'เรียนรู้เทคนิคการเขียนหลักการด้านการขายเพื่อให้สามารถขายผลิตภัณฑ์ได้มากขึ้น', 'เรียนรู้เทคนิคการเขียนหลักการด้านการขายเพื่อให้สามารถขายผลิตภัณฑ์ได้มากขึ้น ด้วยศิลปะแห่งการใช้คำ', '✍️');
INSERT INTO courses (id, name, category, instructor, price, old_price, rating, reviews, lessons, hours, description, short_desc, fullDescription, long_desc, image) VALUES (7, 'How to Go Viral on TikTok', 'TikTok Viral Mastery', 'อลิเศษ อินสตารา', 699, 1199, 4.9, 450, 12, 18, 'สูตรลับการทำวิดีโอให้ไวรัลและเพิ่มผู้ติดตามอย่างรวดเร็ว', 'สูตรลับการทำวิดีโอให้ไวรัลและเพิ่มผู้ติดตามอย่างรวดเร็ว', 'ค้นพบอัลกอริทึม TikTok และวิธีสร้างเนื้อหาที่ได้รับการสนับสนุนจากแพลตฟอร์ม', 'ค้นพบอัลกอริทึม TikTok และวิธีสร้างเนื้อหาที่ได้รับการสนับสนุนจากแพลตฟอร์ม เพื่อก้าวสู่การเป็นครีเอเตอร์', '🎵');
INSERT INTO courses (id, name, category, instructor, price, old_price, rating, reviews, lessons, hours, description, short_desc, fullDescription, long_desc, image) VALUES (8, 'Professional TikTok Content', 'TikTok Content Creation', 'สิตา กมลากร', 599, 999, 4.8, 380, 10, 15, 'สร้างคอนเทนต์มีคุณภาพ ทำให้ผู้ชมติดตามและมีส่วนร่วม', 'สร้างคอนเทนต์มีคุณภาพ ทำให้ผู้ชมติดตามและมีส่วนร่วม', 'สอนวิธีสร้างคอนเทนต์ TikTok ที่มีคุณภาพและสามารถดึงดูดผู้ชม', 'สอนวิธีสร้างคอนเทนต์ TikTok ที่มีคุณภาพและสามารถดึงดูดผู้ชม เพิ่ม Engagement ให้ช่องของคุณเติบโต', '📸');
INSERT INTO courses (id, name, category, instructor, price, old_price, rating, reviews, lessons, hours, description, short_desc, fullDescription, long_desc, image) VALUES (9, 'Earn Money on TikTok', 'TikTok Monetization', 'ศรัณย์ มัสยา', 899, 1499, 4.7, 290, 11, 20, 'วิธีต่างๆ ในการหารายได้จาก TikTok ตั้งแต่ต้น', 'วิธีต่างๆ ในการหารายได้จาก TikTok ตั้งแต่ต้น', 'เรียนรู้วิธีต่างๆ ในการหารายได้จากแพลตฟอร์ม TikTok', 'เรียนรู้วิธีต่างๆ ในการหารายได้จากแพลตฟอร์ม TikTok อย่างละเอียด ตั้งแต่เริ่มต้นจนสามารถสร้างรายได้', '💰');
